deployment:
  tasks:
    # Build React app first
    - export DEPLOYPATH=/home/mpbusis6k1d8/public_html/
    - cd $DEPLOYPATH
    - rm -rf *
    
    # Deploy React build
    - cd /home/mpbusis6k1d8/repositories/MPBusinessHub/client
    - npm install
    - npm run build
    - cp -R dist/* $DEPLOYPATH
    
    # Deploy Laravel backend
    - export SERVERPATH=/home/mpbusis6k1d8/public_html/server
    - mkdir -p $SERVERPATH
    - cd /home/mpbusis6k1d8/repositories/MPBusinessHub/server
    - cp -R * $SERVERPATH/
    - cp ../.env.production $SERVERPATH/.env
    
    # Install Laravel dependencies
    - cd $SERVERPATH
    - composer install --no-dev --optimize-autoloader
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    
    # Set permissions
    - chmod -R 755 storage
    - chmod -R 755 bootstrap/cache