deployment:
  tasks:
    # Deploy React frontend
    - export DEPLOYPATH=/home/mpbusis6k1d8/public_html/
    - /bin/cp -R /home/mpbusis6k1d8/repositories/MPBusinessHub/client/dist/* $DEPLOYPATH

    # Deploy Laravel backend
    - export SERVERPATH=/home/mpbusis6k1d8/public_html/server
    - mkdir -p $SERVERPATH
    - /bin/cp -R /home/mpbusis6k1d8/repositories/MPBusinessHub/server/* $SERVERPATH/
    - /bin/cp /home/mpbusis6k1d8/repositories/MPBusinessHub/.env.production $SERVERPATH/.env