# docker-compose.yml
version: '3'
services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: mpbusinesshub
    container_name: mpbusinesshub-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./server:/var/www/html
    networks:
      - mpbusinesshub

  db:
    image: postgres:13
    container_name: mpbusinesshub-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - mpbusinesshub

  nginx:
    image: nginx:alpine
    container_name: mpbusinesshub-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./server:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - mpbusinesshub

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mpbusinesshub-client
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - mpbusinesshub

networks:
  mpbusinesshub:
    driver: bridge

volumes:
  dbdata:
    driver: local