version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - CI=true
      - VITE_API_URL=http://server:8000/api

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - APP_ENV=testing
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=testing
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./nginx/prod:/etc/nginx/conf.d
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=testing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres