version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: mpbusinesshub/client:latest
    restart: always
    environment:
      - VITE_API_URL=https://api.mpbusinesshub.co.za

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    image: mpbusinesshub/server:latest
    restart: always
    environment:
      - APP_ENV=production
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - /var/www/html/storage:/var/www/html/storage

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - client
      - server