version: '3'

services:
  server:
    build:
      context: ./server
    volumes:
      - ./server:/var/www
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_URL=${APP_URL}
      - FRONTEND_URL=${FRONTEND_URL}

  client:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - server

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./server:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - server

volumes:
  postgres_data: