services:
  # Backend API service
  - type: web
    name: mpbusinesshub-api
    env: docker
    dockerfilePath: server/Dockerfile
    dockerContext: .
    plan: standard
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          name: mpbusinesshub-api
          type: web
          property: url
      - key: FRONTEND_URL
        fromService:
          name: mpbusinesshub-frontend
          type: web
          property: url
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          name: mpbusinesshub-db
          type: pserv
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromService:
          name: mpbusinesshub-db
          type: pserv
          property: database
      - key: DB_USERNAME
        fromService:
          name: mpbusinesshub-db
          type: pserv
          property: username
      - key: DB_PASSWORD
        fromService:
          name: mpbusinesshub-db
          type: pserv
          property: password
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.mailtrap.io
      - key: MAIL_PORT
        value: 2525
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: info@mpbusinesshub.co.za

  # Frontend service
  - type: web
    name: mpbusinesshub-frontend
    env: docker
    dockerfilePath: client/Dockerfile
    dockerContext: .
    plan: standard
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: mpbusinesshub-api
          type: web
          property: url

  # PostgreSQL database
  - type: pserv
    name: mpbusinesshub-db
    env: docker
    repo: https://github.com/render-examples/postgres
    plan: standard
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
    envVars:
      - key: POSTGRES_USER
        generateValue: true
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: POSTGRES_DB
        value: mpbusinesshub