FROM php:8.2-fpm

# Install required packages
RUN apt-get update && apt-get install -y \
    nginx \
    supervisor \
    && apt-get clean

# Configure Nginx
COPY ../nginx/prod/default.conf /etc/nginx/conf.d/default.conf

# Configure Supervisor
COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Set working directory
WORKDIR /var/www/html

# Expose ports
EXPOSE 80 443

# Start Supervisor
CMD ["/usr/bin/supervisord"]