name: MPBusinessHub CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: testing
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Build and test with Docker Compose
      run: |
        docker-compose -f docker-compose.test.yml up -d --build
        docker-compose -f docker-compose.test.yml exec -T server php artisan test
        docker-compose -f docker-compose.test.yml exec -T client npm test
        docker-compose -f docker-compose.test.yml down

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Build and push Docker images
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker-compose -f docker-compose.prod.yml build
        docker-compose -f docker-compose.prod.yml push